---
title: "MechaCarChallenge"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Deliverable 1

```{r}
library(dplyr)
library(ggplot2)
mecha_table <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
```

#Multiple regression

```{r}
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=mecha_table) #generate multiple linear regression model
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=mecha_table)) #generate summary statistics
```
#Tests for normality and look at correlations for significant variables

```{r}
# Check for normality
ggplot(mecha_table,aes(x=vehicle_length)) + geom_density() #visualize distribution using density plot
shapiro.test(mecha_table$vehicle_length)

ggplot(mecha_table,aes(x=ground_clearance)) + geom_density() 
shapiro.test(mecha_table$ground_clearance)

# Plot relationships with significant vars and mpg
ggplot(mecha_table, aes(x=vehicle_length, y=mpg)) +
  geom_point(size=2)

ggplot(mecha_table, aes(x=ground_clearance, y=mpg)) +
  geom_point(size=2)
```
# Deliverable 2

```{r}
coil_table <- read.csv(file='Suspension_Coil.csv',check.names=F,stringsAsFactors = F)

total_summary <- coil_table %>% summarize(Mean =mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI)) #create summary table
total_summary

lot_summary <- coil_table %>% group_by(Manufacturing_Lot) %>% summarize(Mean =mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI))
lot_summary
```
# Deliverable 3
```{r}
# One-sample t-test
# Ho = (mean PSI = 1500)
res <- t.test(coil_table$PSI,alternative = "two.sided", mu = 1500)
# Printing the results
res
```

```{r}
# subset the data for each lot
lot1 <- subset(coil_table, Manufacturing_Lot == 'Lot1')
lot2 <- subset(coil_table, Manufacturing_Lot == 'Lot2')
lot3 <- subset(coil_table, Manufacturing_Lot == 'Lot3')

# One-sample t-test for each lot
# Ho = (mean PSI = 1500)

# One sample t tests for each lot
res1 <- t.test(lot1$PSI,alternative = "two.sided", mu = 1500)
# Printing the results
res1

res2 <- t.test(lot2$PSI,alternative = "two.sided", mu = 1500)
# Printing the results
res2

res3 <- t.test(lot3$PSI,alternative = "two.sided", mu = 1500)
# Printing the results
res3
```

